#!/bin/bash

# postinst
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

case "$1" in
    configure)
    # Nothing here anymore
    ;;

esac

#DEBHELPER#

exit 0
