#!/bin/bash

# postinst
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

TMP_WOLFRAM_FILE=/tmp/wolfram-installer_conf
TMP_LIBREOFFICE_FILE=/tmp/libreoffice-installer_conf
    case "$1" in
        configure)
        # Create custom sudoers file for Wolfram
        echo "%sudo ALL=(root) NOPASSWD: /usr/bin/wolfram-installer" > $TMP_WOLFRAM_FILE
        # The owner and group for the sudoers file must both be 0
        chown root:root $TMP_WOLFRAM_FILE
        # The file permissions must be set to 0440
        chmod 0440 $TMP_WOLFRAM_FILE
        # Move the file to the sudoers directory
        mv $TMP_WOLFRAM_FILE /etc/sudoers.d/

        # Create custom sudoers file for LibreOffice
        echo "%sudo ALL=(root) NOPASSWD: /usr/bin/libreoffice-installer" > $TMP_LIBREOFFICE_FILE
        chown root:root $TMP_LIBREOFFICE_FILE
        chmod 0440 $TMP_LIBREOFFICE_FILE
        mv $TMP_LIBREOFFICE_FILE /etc/sudoers.d/

        # Create symbolic link in /etc/skel
        ln -s /usr/share/kano-extras/books /etc/skel/books
    ;;

esac

#DEBHELPER#

exit 0
