#!/bin/bash

# postinst
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

case "$1" in
    configure)
        update-app-dir
    ;;

    triggered)
        update-app-dir
    ;;
esac

#DEBHELPER#

exit 0
