#!/bin/bash

# postrm
#
# Copyright (C) 2014 Kano Computing Ltd.
# License:   http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

case "$1" in
    remove|upgrade)
        # Remove Wolfram config file in sudoers
        rm /etc/sudoers.d/wolfram-installer_conf

        # Remove LibreOffice config file in sudoers
        rm /etc/sudoers.d/libreoffice-installer_conf

        # Removing symbolic link
        rm -f /etc/skel/books

    ;;
esac

#DEBHELPER#

exit 0
